# Generated by Django 4.2.13 on 2026-06-02 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_department_user_email_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmapping',
            name='dorm_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_dorms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classmapping',
            name='dorm_manager_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', '学生'), ('dorm_manager', '宿管员'), ('counselor', '辅导员'), ('dean', '学工部')], max_length=20),
        ),
    ]
