# Generated by Django 4.2.13 on 2026-06-02 19:42

from django.db import migrations


def backfill_dorm_manager(apps, schema_editor):
    ClassMapping = apps.get_model("users", "ClassMapping")
    for mapping in ClassMapping.objects.filter(dorm_manager__isnull=True):
        mapping.dorm_manager_id = mapping.counselor_id
        mapping.dorm_manager_name = mapping.counselor_name
        mapping.save(update_fields=["dorm_manager", "dorm_manager_name"])


def reverse_backfill(apps, schema_editor):
    ClassMapping = apps.get_model("users", "ClassMapping")
    ClassMapping.objects.all().update(dorm_manager=None, dorm_manager_name=None)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_classmapping_dorm_manager_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_dorm_manager, reverse_backfill),
    ]
