# Generated by Django 5.0 on 2026-06-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_admin_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ClassMapping',
        ),
    ]
