# Generated by manual password fix on 2026-06-27

from django.db import migrations

def fix_empty_passwords(apps, schema_editor):
    """
    修复15990名用户的空密码问题
    注意：此migration记录了已完成的手工修复，执行时会跳过
    """
    User = apps.get_model('users', 'User')

    # 检查是否还有空密码
    empty_count = User.objects.filter(password='').count()

    if empty_count > 0:
        raise Exception(
            f"发现{empty_count}个空密码用户，需要手工修复。"
            "参考文档：docs/数据库备份配置.md"
        )

    # 记录：此migration仅用于验证和记录历史修复
    print(f"密码修复已完成（2026-06-27手工修复）")

class Migration(migrations.Migration):
    dependencies = [
        ('users', '0010_add_test_temp_user'),  # 修正依赖至最新migration
    ]

    operations = [
        migrations.RunPython(fix_empty_passwords),
    ]
