# Generated by Django 4.2.13 on 2026-05-30 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('approval_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('step', models.CharField(choices=[('counselor', '辅导员'), ('dean', '学工部')], max_length=20)),
                ('approver_name', models.CharField(max_length=100)),
                ('decision', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='applications.application')),
            ],
            options={
                'db_table': 'approvals',
            },
        ),
    ]
