# Generated by Django 4.2.13 on 2026-06-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='step',
            field=models.CharField(choices=[('dorm_manager', '宿管员'), ('counselor', '辅导员'), ('dean', '学工部')], max_length=20),
        ),
    ]
