# Generated by Django 4.2.13 on 2026-06-08 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('approvals', '0003_alter_approval_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_approvals', to=settings.AUTH_USER_MODEL, verbose_name='实际审批人'),
        ),
    ]
