# Generated by Django 5.0 on 2026-06-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0004_add_decided_by_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='decision',
            field=models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回'), ('cancelled', '已取消')], default='pending', max_length=20),
        ),
    ]
