# Generated by Django 4.2.13 on 2026-05-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('class_id', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('leave_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_counselor', '待辅导员审批'), ('pending_dean', '待学工部审批'), ('approved', '已通过'), ('rejected', '已驳回')], default='draft', max_length=20)),
                ('dorm_checkout_status', models.CharField(choices=[('completed', '已清退'), ('pending', '清退中'), ('not_started', '未开始'), ('unknown', '状态未知')], default='not_started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'applications',
            },
        ),
    ]
