# Generated by Django 4.2.13 on 2026-05-30 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_unique_student_application'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='application',
            name='unique_student_application',
        ),
    ]
