# Generated by Django 4.2.13 on 2026-06-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='leave_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending_dorm_manager', '待宿管员审批'), ('pending_counselor', '待辅导员审批'), ('approved', '已通过'), ('rejected', '已驳回')], default='draft', max_length=20),
        ),
    ]
