# Generated by Django 5.0 on 2026-06-19 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_allow_null_class_id'),
        ('applications', '0006_application_contact_phone_and_more'),
    ]

    operations = [
    ]
