# Generated by Django 5.0 on 2026-06-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_merge_20260620_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_type',
            field=models.CharField(choices=[('leave_school', '离校申请'), ('stay_school', '留校申请'), ('leave_request', '请假申请')], default='leave_school', max_length=20, verbose_name='申请类型'),
        ),
        migrations.AddField(
            model_name='application',
            name='stay_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='留校结束日期'),
        ),
        migrations.AddField(
            model_name='application',
            name='stay_reason',
            field=models.CharField(blank=True, choices=[('exam_prep', '考公考研'), ('summer_practice', '暑期实践'), ('teacher_exam', '考教师编'), ('huangzhou_intern', '黄州实习'), ('sports_volunteer', '体育比赛志愿服务'), ('challenge_cup', '挑战杯竞赛'), ('college_competition', '学院组织的比赛'), ('mentor_guidance', '导师指导'), ('other', '其它')], max_length=30, null=True, verbose_name='留校原因'),
        ),
        migrations.AddField(
            model_name='application',
            name='stay_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='留校开始日期'),
        ),
        migrations.AlterField(
            model_name='application',
            name='class_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending_dorm_manager', '待宿管员审批'), ('pending_counselor', '待辅导员审批'), ('approved', '已通过'), ('rejected', '已驳回'), ('failed', '提交失败')], default='draft', max_length=20),
        ),
    ]
