# Generated by Django 5.0 on 2026-06-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_application_application_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='class_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
