# Generated by Django 5.0 on 2026-06-08 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SSOUserMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_code', models.CharField(max_length=50, verbose_name='租户Code')),
                ('user_code', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='移动端user_code')),
                ('username', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='管理端username')),
                ('user_type', models.CharField(choices=[('mobile_student', '移动端-学生'), ('mobile_teacher', '移动端-教师'), ('admin', '管理端-管理员')], max_length=20, verbose_name='用户类型')),
                ('real_name', models.CharField(max_length=100, verbose_name='真实姓名')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('identity_name', models.CharField(blank=True, max_length=50, verbose_name='身份名称')),
                ('role_name', models.CharField(blank=True, max_length=100, verbose_name='角色名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sso_mapping', to=settings.AUTH_USER_MODEL, verbose_name='本地用户')),
            ],
            options={
                'verbose_name': 'SSO用户映射',
                'verbose_name_plural': 'SSO用户映射',
                'db_table': 'sso_user_mapping',
                'indexes': [models.Index(fields=['user_code'], name='idx_user_code'), models.Index(fields=['username'], name='idx_username')],
            },
        ),
    ]
